# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Techno Live Co.,Ltd.
paginate:       5
baseurl:        ""
url:            "https://seongchankim.github.io/new"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Techno Live Co.,Ltd.
  url:          https://seongchankim.github.io/new
  email:        kim-seongchan@technolive.co.jp

# Custom vars
version:        3.4.1
github:
  repo:         https://seongchankim.github.io/new

# Gems
gems:
  - jekyll-paginate
