# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          TLHP
paginate:       5
baseurl:        ""
url:            "https://eongchankim.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Chester How
  url:          http://chester.how
  email:        chesterhow@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://eongchankim.github.io

# Gems
gems:
  - jekyll-paginate
